#! /bin/bash
# Sai imediatamente se um comando sai com um status não-zero.
set -e

# Importações das funções utilitárias.
source util/is-helm-chart-installed.sh

# Implantação do Longhorn.
if [[ -z "$(isHelmChartInstalled databases postgresql)" && "$isPostgreSQLEnabled" == "true" ]]
then
cat << EOF | helm upgrade postgresql bitnami/postgresql --install --create-namespace --namespace=databases --version=11.9.13 --values -
tls:
  enabled: true
  autoGenerated: true
EOF
echo "O MailHog foi implantado com sucesso."
elif [ "$isPostgreSQLEnabled" == "true" ]
then
echo "O MailHog já está implantado."
fi