#! /bin/bash
# Sai imediatamente se um comando sai com um status não-zero.
set -e

# Importações das funções utilitárias.
source util/is-helm-chart-installed.sh

# Implantação do PostgreSQL.
if [[ -z "$(isHelmChartInstalled databases postgresql)" && "$isPostgreSQLEnabled" == "true" ]]
then
echo "Implantação do PostgreSQL."

if [ -z "$(helm repo list --output yaml | yq '.[] | select(.name == "bitnami").name')" ]
then
helm repo add bitnami https://charts.bitnami.com/bitnami
fi

cat << EOF | helm upgrade postgresql bitnami/postgresql --install --create-namespace --namespace=databases --version=11.9.13 --values -
tls:
  enabled: true
  autoGenerated: true
EOF
echo "O PostgreSQL foi implantado com sucesso."
elif [ "$isPostgreSQLEnabled" == "true" ]
then
echo "O PostgreSQL já está implantado."
fi